<?php
declare(strict_types=1);

/* Cyberpro Global API for PHP hosting (PHP 8.1+, PDO SQLite or MySQL). */
const ROOT = __DIR__;
const MAX_UPLOAD_BYTES = 10485760;
if (is_file(__DIR__ . '/admin.php')) require_once __DIR__ . '/admin.php';

function env_value(string $name, ?string $default = null): ?string { $value = getenv($name); return $value === false || $value === '' ? $default : $value; }
function json_response(mixed $data, int $status = 200): never { http_response_code($status); header('Content-Type: application/json; charset=utf-8'); echo json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_INVALID_UTF8_SUBSTITUTE); exit; }
function fail(int $status, string $message, array $headers = []): never { foreach ($headers as $key => $value) header("$key: $value"); json_response(['detail' => $message], $status); }
function db(): PDO {
    static $pdo = null; if ($pdo instanceof PDO) return $pdo;
    $dsn = env_value('DATABASE_DSN');
    if (!$dsn) { $path = env_value('SQLITE_PATH', ROOT . '/data/cyberpro.db'); $dir = dirname($path); if (!is_dir($dir) && !mkdir($dir, 0700, true) && !is_dir($dir)) throw new RuntimeException('Cannot create SQLite data directory'); if (!is_file($path)) { $handle = @fopen($path, 'x'); if ($handle !== false) { fclose($handle); @chmod($path, 0600); } } $dsn = 'sqlite:' . $path; }
    $user = env_value('DATABASE_USER'); $pass = env_value('DATABASE_PASSWORD');
    $pdo = new PDO($dsn, $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_EMULATE_PREPARES => false]);
    if (str_starts_with($dsn, 'sqlite:')) $pdo->exec('PRAGMA foreign_keys = ON');
    return $pdo;
}
function tables(): array { return [
 'admin_users'=>['username'=>'TEXT NOT NULL UNIQUE','hashed_password'=>'TEXT NOT NULL'],
 'programs'=>['title'=>'TEXT NOT NULL','desc'=>'TEXT NOT NULL','cat'=>'TEXT NOT NULL','dur'=>'TEXT NOT NULL','date'=>'TEXT NOT NULL','lvl'=>'TEXT NOT NULL','fee'=>'TEXT NOT NULL','certs'=>'TEXT NOT NULL','img'=>'TEXT NOT NULL','sourceUrl'=>'TEXT NOT NULL'],
 'events'=>['title'=>'TEXT NOT NULL','date'=>'TEXT NOT NULL','type'=>'TEXT NOT NULL','cat'=>'TEXT NOT NULL','desc'=>'TEXT NOT NULL','color'=>'TEXT NOT NULL','img'=>'TEXT NOT NULL','link'=>'TEXT NULL'],
 'articles'=>['title'=>'TEXT NOT NULL','excerpt'=>'TEXT NOT NULL','content'=>'TEXT NOT NULL','cat'=>'TEXT NOT NULL','catLabel'=>'TEXT NOT NULL','date'=>'TEXT NOT NULL','read'=>'TEXT NOT NULL','author'=>'TEXT NOT NULL','img'=>'TEXT NOT NULL','featured'=>'INTEGER NOT NULL DEFAULT 0'],
 'research_clusters'=>['title'=>'TEXT NOT NULL','desc'=>'TEXT NOT NULL','lead'=>'TEXT NOT NULL','icon'=>"TEXT NOT NULL DEFAULT 'FlaskConical'"],
 'publications'=>['title'=>'TEXT NOT NULL','authors'=>'TEXT NOT NULL','venue'=>'TEXT NOT NULL','type'=>'TEXT NOT NULL','link'=>'TEXT NULL'],
 'gallery_items'=>['caption'=>'TEXT NOT NULL','img'=>'TEXT NOT NULL'],
 'media_assets'=>['filename'=>'TEXT NOT NULL UNIQUE','original_name'=>'TEXT NOT NULL','content_type'=>'TEXT NOT NULL','size_bytes'=>'INTEGER NOT NULL','created_at'=>'TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP'],
 'corporate_services'=>['title'=>'TEXT NOT NULL','desc'=>'TEXT NOT NULL','icon'=>"TEXT NOT NULL DEFAULT 'Building2'"],
 'corporate_metrics'=>['value'=>'TEXT NOT NULL','label'=>'TEXT NOT NULL'],
 'corporate_inquiries'=>['company'=>'TEXT NOT NULL','contact_name'=>'TEXT NOT NULL','email'=>'TEXT NOT NULL','team_size'=>'TEXT NOT NULL','created_at'=>'TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP'],
 'contact_messages'=>['name'=>'TEXT NOT NULL','email'=>'TEXT NOT NULL','phone'=>'TEXT NULL','program'=>'TEXT NULL','message'=>'TEXT NOT NULL','created_at'=>'TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP'],
 'applications'=>['fullName'=>'TEXT NOT NULL','email'=>'TEXT NOT NULL','phone'=>'TEXT NOT NULL','location'=>'TEXT NOT NULL','program'=>'TEXT NOT NULL','classFormat'=>'TEXT NOT NULL','studyMode'=>'TEXT NOT NULL','paymentPlan'=>'TEXT NOT NULL','startDate'=>'TEXT NULL','experienceLevel'=>'TEXT NOT NULL','notes'=>'TEXT NULL','created_at'=>'TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP'],
 ]; }
function initialize_db(): void { static $done=false; if($done)return; $pdo=db(); $mysql=$pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql'; foreach(tables() as $name=>$columns){ $defs=['id '.($mysql?'INT AUTO_INCREMENT PRIMARY KEY':'INTEGER PRIMARY KEY AUTOINCREMENT')]; foreach($columns as $col=>$type){ if($mysql){$type=str_replace('INTEGER','INT',$type); if($col==='featured')$type='TINYINT(1) NOT NULL DEFAULT 0'; if(str_ends_with($type,'TEXT'))$type='VARCHAR(1000)'.(str_contains($type,'NOT NULL')?' NOT NULL':' NULL'); if(in_array($col,['desc','excerpt','content','message','notes'],true))$type='LONGTEXT'.(str_contains($type,'NOT NULL')?' NOT NULL':' NULL'); if($col==='created_at')$type='DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'; } $defs[]='`'.$col.'` '.$type; } $pdo->exec('CREATE TABLE IF NOT EXISTS `'.$name.'` ('.implode(',',$defs).')'); } $done=true; }
function body_json(): array { $raw=file_get_contents('php://input'); $data=json_decode($raw ?: '[]',true); if(!is_array($data)) fail(422,'Invalid JSON body'); return $data; }
function validate_data(string $table,array $data): array {
    $rules=[
      'programs'=>['title'=>[1,255],'desc'=>[1,10000],'cat'=>[1,80],'dur'=>[1,120],'date'=>[1,120],'lvl'=>[1,120],'fee'=>[1,120],'certs'=>[0,500],'img'=>[0,1000],'sourceUrl'=>[0,1000]],
      'events'=>['title'=>[1,255],'date'=>[1,120],'type'=>[1,80],'cat'=>[1,80],'desc'=>[1,10000],'color'=>[0,80],'img'=>[0,1000],'link'=>[0,1000]],
      'articles'=>['title'=>[1,255],'excerpt'=>[1,2000],'content'=>[1,50000],'cat'=>[1,80],'catLabel'=>[1,120],'date'=>[1,120],'read'=>[0,40],'author'=>[1,160],'img'=>[0,1000],'featured'=>[0,1]],
      'research_clusters'=>['title'=>[1,255],'desc'=>[1,10000],'lead'=>[1,160],'icon'=>[0,80]],'publications'=>['title'=>[1,500],'authors'=>[1,500],'venue'=>[1,255],'type'=>[1,80],'link'=>[0,1000]],'gallery_items'=>['caption'=>[1,255],'img'=>[1,1000]],'corporate_services'=>['title'=>[1,255],'desc'=>[1,3000],'icon'=>[0,80]],'corporate_metrics'=>['value'=>[1,80],'label'=>[1,160]],
      'corporate_inquiries'=>['company'=>[1,255],'contact_name'=>[1,160],'email'=>[1,254],'team_size'=>[1,80]],'contact_messages'=>['name'=>[1,160],'email'=>[1,254],'phone'=>[0,40],'program'=>[0,255],'message'=>[1,10000]],'applications'=>['fullName'=>[1,160],'email'=>[1,254],'phone'=>[3,40],'location'=>[1,160],'program'=>[1,255],'classFormat'=>[1,80],'studyMode'=>[1,80],'paymentPlan'=>[1,80],'startDate'=>[0,40],'experienceLevel'=>[1,80],'notes'=>[0,10000]],
    ];
    $schema=$rules[$table]??[]; $out=[]; foreach($schema as $key=>[$min,$max]) { $value=$data[$key]??null; if($key==='featured'){$value=(bool)$value;} elseif($value===null && $min===0){$value=null;} elseif(!is_string($value)) fail(422,"$key is required"); if(is_string($value)){ $value=trim($value); $length=function_exists('mb_strlen')?mb_strlen($value):strlen($value); if($length>$max || ($min>0 && $length<$min)) fail(422,"Invalid $key"); } if($key==='email' && $value!==null && !filter_var($value,FILTER_VALIDATE_EMAIL)) fail(422,'Invalid email address'); if(in_array($key,['icon'],true) && $value==='')$value=$table==='corporate_services'?'Building2':'FlaskConical'; $out[$key]=$value; }
    foreach(['corporate_inquiries','contact_messages','applications'] as $publicTable) if($table===$publicTable && $out['email']!==null)$out['email']=strtolower($out['email']); return $out;
}
function admin_user(): array { $header=$_SERVER['HTTP_AUTHORIZATION']??''; if(!preg_match('/^Bearer\s+(.+)$/i',$header,$m))fail(401,'Not authenticated',['WWW-Authenticate'=>'Bearer']); $payload=decode_token($m[1]); $username=$payload['sub']??''; if(!is_string($username)||!str_ends_with(strtolower($username),'@cyberpro.ke'))fail(401,'Could not validate credentials',['WWW-Authenticate'=>'Bearer']); $st=db()->prepare('SELECT id,username FROM admin_users WHERE username=?');$st->execute([$username]);$user=$st->fetch();if(!$user)fail(401,'Could not validate credentials',['WWW-Authenticate'=>'Bearer']);return $user; }
function require_admin(): array { return admin_user(); }
function b64url(string $v): string { return rtrim(strtr(base64_encode($v),'+/','-_'),'='); }
function decode_token(string $token): array { $parts=explode('.',$token); if(count($parts)!==3)fail(401,'Could not validate credentials',['WWW-Authenticate'=>'Bearer']); [$head,$payload,$sig]=$parts; $secret=env_value('SECRET_KEY','local-development-only-change-before-deployment'); $expected=b64url(hash_hmac('sha256',"$head.$payload",$secret,true)); if(!hash_equals($expected,$sig))fail(401,'Could not validate credentials',['WWW-Authenticate'=>'Bearer']); $decoded=json_decode(base64_decode(strtr($payload,'-_','+/').str_repeat('=',(4-strlen($payload)%4)%4)),true); if(!is_array($decoded)||($decoded['exp']??0)<time())fail(401,'Could not validate credentials',['WWW-Authenticate'=>'Bearer']);return $decoded; }
function make_token(string $username): string { $secret=env_value('SECRET_KEY','local-development-only-change-before-deployment');$h=b64url('{"alg":"HS256","typ":"JWT"}');$p=b64url(json_encode(['sub'=>$username,'exp'=>time()+3600],JSON_UNESCAPED_SLASHES));return "$h.$p.".b64url(hash_hmac('sha256',"$h.$p",$secret,true)); }
function send_admin_password(array $data): never { $username=strtolower(trim((string)($data['username']??'')));$password=$data['password']??'';if(!filter_var($username,FILTER_VALIDATE_EMAIL)||!str_ends_with($username,'@cyberpro.ke')||!is_string($password)||$password==='')fail(422,'Use your @cyberpro.ke administrator email and enter a password');$st=db()->prepare('SELECT * FROM admin_users WHERE username=?');$st->execute([$username]);$user=$st->fetch();if(!$user||!verify_legacy_password($password,$user['hashed_password']))fail(401,'Incorrect username or password',['WWW-Authenticate'=>'Bearer']);json_response(['access_token'=>make_token($username),'token_type'=>'bearer']); }
function verify_legacy_password(string $password,string $stored): bool { $parts=explode('$',$stored);if(count($parts)!==4||$parts[0]!=='pbkdf2_sha256')return password_verify($password,$stored);$salt=base64_decode(strtr($parts[2],'-_','+/').str_repeat('=',(4-strlen($parts[2])%4)%4));$hash=hash_pbkdf2('sha256',$password,$salt,(int)$parts[1],0,true);return hash_equals($parts[3],rtrim(strtr(base64_encode($hash),'+/','-_'),'=')); }
function query_all(string $table,string $order): array { $allowed=array_keys(tables());if(!in_array($table,$allowed,true))fail(404,'Not found');return db()->query("SELECT * FROM `$table` ORDER BY $order")->fetchAll(); }
function clean_row(array $row): array { if(isset($row['featured']))$row['featured']=(bool)$row['featured'];return $row; }
function save_row(string $table,int $id,array $data): array { $row=validate_data($table,$data);$pdo=db();if($id){$st=$pdo->prepare("SELECT id FROM `$table` WHERE id=?");$st->execute([$id]);if(!$st->fetch())fail(404,ucfirst(str_replace('_',' ',$table)).' not found');$pairs=array_map(fn($k)=>"`$k`=?",array_keys($row));$st=$pdo->prepare("UPDATE `$table` SET ".implode(',',$pairs).' WHERE id=?');$st->execute([...array_values($row),$id]);}else{$cols=array_keys($row);$st=$pdo->prepare("INSERT INTO `$table` (`".implode('`,`',$cols).'`) VALUES ('.implode(',',array_fill(0,count($cols),'?')).')');$st->execute(array_values($row));$id=(int)$pdo->lastInsertId();} $st=$pdo->prepare("SELECT * FROM `$table` WHERE id=?");$st->execute([$id]);return clean_row($st->fetch()); }
function delete_row(string $table,int $id,string $label): never { $st=db()->prepare("DELETE FROM `$table` WHERE id=?");$st->execute([$id]);if(!$st->rowCount())fail(404,"$label not found");http_response_code(204);exit; }
function media_dir(): string { $dir=env_value('MEDIA_DIR',ROOT.'/uploads');if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Cannot create uploads directory');return rtrim($dir,'/'); }
function route_request(): never {
    initialize_db();$method=$_SERVER['REQUEST_METHOD']??'GET';$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';
    if($method==='OPTIONS'){http_response_code(204);exit;} if(preg_match('#^/media/([a-f0-9]{32}\.(?:jpg|png|webp|gif))$#',$path,$mediaMatch)&&$method==='GET'){ $file=media_dir().'/'.$mediaMatch[1];if(!is_file($file))fail(404,'Image not found');header('Content-Type: '.(new finfo(FILEINFO_MIME_TYPE))->file($file));header('X-Content-Type-Options: nosniff');readfile($file);exit; }
    if($path==='/health'&&$method==='GET'){db()->query('SELECT 1');json_response(['status'=>'ok']);}if($path==='/'&&$method==='GET')json_response(['name'=>'Cyberpro Global API','version'=>'1.0.0','docs'=>null]);
    if($path==='/api/admin/login'&&$method==='POST')send_admin_password(body_json());if($path==='/api/admin/me'&&$method==='GET')json_response(require_admin());
    $routeMap=['programs'=>['programs','id'],'events'=>['events','id'],'articles'=>['articles','id'],'research/clusters'=>['research_clusters','id'],'research/publications'=>['publications','id'],'gallery'=>['gallery_items','id'],'corporate/services'=>['corporate_services','id'],'corporate/metrics'=>['corporate_metrics','id'],'corporate/inquiries'=>['corporate_inquiries','id'],'contact'=>['contact_messages','id'],'applications'=>['applications','id']];
    foreach($routeMap as $route=>[$table,$param])if(preg_match('#^/api/'.preg_quote($route,'#').'(?:/(\d+))?$#',$path,$match)){ $id=(int)($match[1]??0);$adminOnly=!in_array($route,['programs','events','articles','research/clusters','research/publications','gallery','corporate/services','corporate/metrics'],true)||$method!=='GET';if($adminOnly)require_admin();if($method==='GET'&&!$id){$order=match($route){'articles'=>'id DESC','corporate/inquiries','contact','applications'=>'created_at DESC',default=>'id ASC'};json_response(array_map('clean_row',query_all($table,$order)));}if($method==='POST'&&!$id)json_response(save_row($table,0,body_json()),201);if($method==='PUT'&&$id)json_response(save_row($table,$id,body_json()));if($method==='DELETE'&&$id)delete_row($table,$id,ucfirst(str_replace('_',' ',$table)));fail(405,'Method not allowed'); }
    if($path==='/api/media'&&$method==='GET'){require_admin();$rows=query_all('media_assets','created_at DESC');$base=rtrim(env_value('MEDIA_BASE_URL',((!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost')),'/');foreach($rows as &$row)$row['url']=$base.'/media/'.$row['filename'];json_response($rows);}
    if($path==='/api/media'&&$method==='POST'){require_admin();if(!isset($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK)fail(422,'Choose an image to upload');$f=$_FILES['file'];$type=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$types=['image/jpeg'=>['jpg',"\xFF\xD8\xFF"],'image/png'=>['png',"\x89PNG\r\n\x1a\n"],'image/webp'=>['webp','RIFF'],'image/gif'=>['gif','GIF']];if(!isset($types[$type]))fail(415,'Upload a JPEG, PNG, WebP, or GIF image');if($f['size']>MAX_UPLOAD_BYTES)fail(413,'Image must be 10 MB or smaller');$bytes=file_get_contents($f['tmp_name']);[$ext,$sig]=$types[$type];if(!str_starts_with($bytes,$sig)||($type==='image/webp'&&substr($bytes,8,4)!=='WEBP'))fail(415,'The file contents do not match the selected image type');$filename=bin2hex(random_bytes(16)).'.'.$ext;if(!move_uploaded_file($f['tmp_name'],media_dir().'/'.$filename))fail(500,'Unable to save image');$st=db()->prepare('INSERT INTO media_assets(filename,original_name,content_type,size_bytes) VALUES(?,?,?,?)');$st->execute([$filename,substr(basename($f['name']),0,255),$type,strlen($bytes)]);$id=(int)db()->lastInsertId();$base=rtrim(env_value('MEDIA_BASE_URL',((!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost')),'/');json_response(['id'=>$id,'filename'=>$filename,'original_name'=>substr(basename($f['name']),0,255),'content_type'=>$type,'size_bytes'=>strlen($bytes),'created_at'=>date('Y-m-d H:i:s'),'url'=>$base.'/media/'.$filename],201);}
    if(preg_match('#^/api/media/(\d+)$#',$path,$m)&&$method==='DELETE'){require_admin();$id=(int)$m[1];$st=db()->prepare('SELECT filename FROM media_assets WHERE id=?');$st->execute([$id]);$f=$st->fetch();if(!$f)fail(404,'Image not found');db()->prepare('DELETE FROM media_assets WHERE id=?')->execute([$id]);@unlink(media_dir().'/'.$f['filename']);http_response_code(204);exit;}
    fail(404,'Not found');
}
try { route_request(); } catch (Throwable $e) { error_log((string)$e);fail(500,'Internal server error'); }
